### PR TITLE
Better DX

### PR DESCRIPTION
**Pull request by laksith19**
Added a docker compose file and updated readme for an improved developer experience.

### CODE REVIEW

**Comment by laksith19** [comment]
Docker compose for PL and autograder has been tested and verified to be working on Windows (powershell and WSL2) and Linux (Fedora 36 & Debian 11).

**Comment by mverdicchio** [comment]
So the new WSL2 command worked great. grading successfully worked on ubuntu/wsl2/win11.
```
docker run -it --rm \
    -p 3000:3000 \
    -v "/tmp/directory/for/autograder/jobqueue":"/jobs" \
    -e HOST_JOBS_DIR="/tmp/directory/for/autograder/jobqueue" \
    -v `pwd`:/course \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --add-host=host.docker.internal:172.17.0.1 \
    prairielearn/prairielearn:latest
```

But when I tried to start `docker compose up` I got this error: `no configuration file provided: not found`

I ignored it and the command above worked fine, so I'm not sure what the issue with compose might be.

**Comment by laksith19** [comment]
That would work only after the pr had been merged as it need a config file that I added not present in the repo at the moment.

**Comment by mverdicchio** [comment]
Oh man I'm dumb. didn't notice the new yaml file that obv wasnt in the main repo.

**Comment by mverdicchio** [comment]
pulled the fork, tested, works great, merging!

**Pull request merged**
